create extension if not exists vector;

create table if not exists users (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    user_id varchar(255) not null unique,
    display_name varchar(255) not null,
    email varchar(255) not null,
    password_hash varchar(255) not null,
    redaction_enabled boolean not null,
    sample_data_initialized boolean not null default false
);

create table if not exists cards (
    id uuid primary key,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    user_fk bigint not null references users(id),
    title varchar(255) not null,
    summary varchar(255),
    content text not null,
    card_type varchar(255) not null,
    status varchar(255) not null,
    priority varchar(255) not null,
    due_date date,
    source_message_id uuid,
    constraint uk_cards_id_user_fk unique (id, user_fk),
    constraint cards_card_type_check check (card_type in ('TASK', 'REMINDER', 'NOTE', 'CONTACT', 'DECISION', 'FOLLOW_UP', 'ALERT')),
    constraint cards_status_check check (status in ('OPEN', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'ARCHIVED')),
    constraint cards_priority_check check (priority in ('LOW', 'MEDIUM', 'HIGH', 'URGENT'))
);

create table if not exists card_embeddings (
    id uuid primary key,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    card_fk uuid not null,
    user_fk bigint not null references users(id),
    embedding_model varchar(255) not null,
    chunking_strategy varchar(255) not null,
    chunk_index integer not null,
    chunk_type varchar(255) not null,
    chunk_text text not null,
    embedding_vector vector(3072) not null,
    constraint fk_card_embeddings_card_owner foreign key (card_fk, user_fk) references cards(id, user_fk),
    constraint card_embeddings_chunk_type_check check (chunk_type in ('SUMMARY', 'CONTENT'))
);

create table if not exists messages (
    id uuid primary key,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    user_fk bigint not null references users(id),
    source_service varchar(255) not null,
    external_message_id varchar(255),
    message_type varchar(255) not null,
    status varchar(255) not null,
    payload text not null,
    summary varchar(280),
    metadata_json jsonb,
    details_json jsonb,
    ingested_at timestamptz not null,
    source_created_at timestamptz,
    constraint messages_status_check check (status in ('PENDING', 'PROCESSING', 'FAILED', 'SUCCESS'))
);

create table if not exists agent_configs (
    id uuid primary key,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    user_fk bigint not null references users(id),
    name varchar(255) not null,
    description text not null,
    prompt text not null,
    model varchar(255) not null,
    temperature double precision not null,
    constraint uk_agent_configs_user_name unique (user_fk, name)
);

create table if not exists orchestrator_configs (
    id uuid primary key,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    user_fk bigint not null unique references users(id),
    filtering_prompt text not null,
    filtering_model varchar(255) not null,
    routing_prompt text not null,
    routing_model varchar(255) not null
);

create table if not exists orchestration_active_agents (
    orchestration_config_fk uuid not null references orchestrator_configs(id),
    agent_fk uuid not null references agent_configs(id),
    primary key (orchestration_config_fk, agent_fk)
);

alter table if exists card_embeddings
    alter column embedding_vector type vector(3072)
    using embedding_vector::vector(3072);

create index if not exists idx_cards_user_updated_at
    on cards (user_fk, updated_at desc);

create index if not exists idx_cards_user_status_updated_at
    on cards (user_fk, status, updated_at desc);

create index if not exists idx_cards_search
    on cards using gin (
        to_tsvector(
            'english',
            coalesce(title, '') || ' ' ||
            coalesce(summary, '') || ' ' ||
            coalesce(content, '')
        )
    );

create index if not exists idx_card_embeddings_card_model
    on card_embeddings (card_fk, embedding_model);

create index if not exists idx_card_embeddings_user_model_card
    on card_embeddings (user_fk, embedding_model, card_fk);

create index if not exists idx_card_embeddings_vector_cosine
    on card_embeddings using hnsw ((embedding_vector::halfvec(3072)) halfvec_cosine_ops);

create index if not exists idx_messages_status_ingested_at
    on messages (status, ingested_at asc);

create index if not exists idx_messages_user_ingested_at
    on messages (user_fk, ingested_at desc);

create index if not exists idx_messages_user_status_ingested_at
    on messages (user_fk, status, ingested_at desc);

create index if not exists idx_messages_user_source_service_ingested_at
    on messages (user_fk, source_service, ingested_at desc);

create index if not exists idx_messages_user_message_type_ingested_at
    on messages (user_fk, message_type, ingested_at desc);

create index if not exists idx_messages_search
    on messages using gin (
        to_tsvector(
            'english',
            coalesce(payload, '') || ' ' ||
            coalesce(source_service, '') || ' ' ||
            coalesce(external_message_id, '') || ' ' ||
            coalesce(message_type, '')
        )
    );

create index if not exists idx_cards_user_card_type_updated_at
    on cards (user_fk, card_type, updated_at desc);

create index if not exists idx_cards_user_status_card_type_updated_at
    on cards (user_fk, status, card_type, updated_at desc);
